---
title: ''
output: html_document
---

# (PART) Principles {-}

# Coding Principles {-#principles}

The coding principles have been designed to help DASD adopt a unified/consistent approach to writing code, ensuring that our work is high quality, maintainable and reusable and that we are able to collaborate effectively across multiple projects [AMEND].

Note that the specific actions recommended within this document, although grouped under each of the four principles, do overlap between the principles - they have been placed where they were deemed to fit best.

They are guidance, not The Law - there will always be edge cases, but you should expect to be challenged if you go your own way.

---------------------------------------------------

Coding practices should aim to create code that is:  

* Reproducible
  + Measures should be put in place to ensure that code can be run across different machines and over time to produce the same results.  
* Collaborative
  + Projects should be structured in such a way that we can collaborate effectively across multiple projects
  + Code should be structured efficiently so that others can re-use existing code. This ensures consistency in approach and reduces the need for new code to be written and quality assured.  
* Accurate
  + Code should be error free and appropriately quality assured.    
* Understandable
  + Code should be structured, commented and documented to ensure it can be understood easily by others and passed on to others with minimal additional instruction.

---------------------------------------------------

Code should be:
[**Update after rewriting individual sections**]

**1. [Understandable](#understand)**  

* Write a [README](#readme) for your project  
* Use [sensible defaults](#defaults) unless you have a great reason not to
* Write [functions](#functions) where needed  
* [Stylistic](#style):  
  - Apply a [linter](#linter)
  - Ensure [variable names](#names) are meaningful 
  - Code should be [correct, clear and concise](#ccc) 
  - [Handle errors](#errors)  
  - Other team members [are users too](#users) - treat them with respect  

**2. [Accurate](#accurate)**  

* Ensure code is [reviewed](#review)
* Complete [unit testing](#unittest)


**3. [Collaborative](#collaborate)**  

* Use the [github workflow](#versioncontrol) across all projects  
* [Share](#knowledge) the knowledge  


**4. [Reproducible](#reproduce)**  

* Manage [project dependencies](#projdep)
* Optimise for [change](#change)  
* Analyses should be [simple and easy to reproduce](#githash) on another machine.
