--- 
title: "DASD Coding Standards"
author: "Data Science Hub"
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "These are the DASD coding standards."
---
# Reviewer notes

This document is an early attempt at restructuring the current coding standards. At present, every part of the existing coding standards has been incorporated into this document. This is unlikely to be the case for the final product, but I didn't want to lose any essential information early on.

The minimum coding standards have been incorporated into the document [here](#mcstable). The formatting and sizing of the embedded html file isn't ideal at present, but provides an illustration of what could be done. Do we even still need the minimum coding standards? Can we easily put all the requirements in one place rather than splitting into two?

In addition, further information will be added at later stages - particularly in the form of links to external sites that will support the beginner in understanding some of the concepts.

This document hasn't been spellchecked or rigorously tested yet (e.g. that links work etc.). This will be done at a later stage when structure has been agreed.

I've also added a section with the recommended [workflow](#wf). I wonder if this would ideally be brought up to the front of the beginning of the document to illustrate to beginners how each of the sections of the principles fits into their project work?

# Introduction {#intro}

This document contains the Data and Analytical Service Directorate's (DASD) coding standards.  

## Motivation {#motivation}

The DASD coding standards have been developed to help DASD adopt a unified/consistent approach to writing code, ensuring that our work is high quality, maintainable and reusable and that we are able to collaborate effectively across multiple projects.

Coding practices should aim to create code that is:  

* Reproducible
    + Measures should be put in place to ensure that code can be run across different machines and over time to produce the same results. 
* Collaborative  
    + Projects should be structured in such a way that we can collaborate effectively across multiple projects  
    
    + Code should be structured efficiently so that others can re-use existing code. This ensures consistency in approach and reduces the need for new code to be written and quality assured.  
    
* Accurate  
    + Code should be error free and appropriately quality assured.  
    
    
* Understandable  

    + Code should be structured, commented and documented to ensure it can be understood easily by others and passed on to others with minimal additional instruction.

## Guidance structure {#structure}

The first part of this document contains the four coding principles, with additional details on the practical actions people should take to achieve these.

There is the recommended workflow for coding projects - this can be used to aid understanding of the steps that should be taken in a project and how the coding principles fit into the project lifecycle.

The final section includes a checklist of actions to be taken to achieve the principles. This is a condensed list of the material covered in the coding principles section.

## Contributing {#contributing}

If you think that something is missing or not quite right you should either:
1. [Contribute directly](#versioncontrol)
2. [Raise an issue](https://github.com/moj-analytical-services/our-coding-standards/issues)

