---
title: "Review_Notes.Rmd"
output: html_document
---
# Reviewer notes

This document is an early attempt at restructuring the current coding standards. At present, every part of the existing coding standards has been incorporated into this document. This is unlikely to be the case for the final product, but I didn't want to lose any essential information early on.

The minimum coding standards have been incorporated into the document [here](#mcstable). The formatting and sizing of the embedded html file isn't ideal at present, but provides an illustration of what could be done. Do we even still need the minimum coding standards? Can we easily put all the requirements in one place rather than splitting into two?

In addition, further information will be added at later stages - particularly in the form of links to external sites that will support the beginner in understanding some of the concepts.

This document hasn't been spellchecked or rigorously tested yet (e.g. that links work etc.). This will be done at a later stage when structure has been agreed.

I've also added a section with the recommended [workflow](#wf). I wonder if this would ideally be brought up to the front of the beginning of the document to illustrate to beginners how each of the sections of the principles fits into their project work?